# Site
repository: kvadityasrivatsa/kvadityasrivatsa.github.io
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Content configuration version
version: 2

# Personal info
name: KV Aditya Srivatsa
title: Undergraduate Researcher | Teaching Assistant
email: k.v.aditya@research.iiit.ac.in
# email_title: Email (Email title override)
#phone: Your phone number (optional)
# phone_title: Phone (Phone title override)
#website: Your website (eg. https://google.com)(optional)
# website_title: Web (Website title override)

# Dark Mode (true/false/never)
darkmode: false

# Social links
#twitter_username: jekyllrb
github_username:  kvadityasrivatsa
#stackoverflow_username: "11038232"
#instagram_username: jekyll
linkedin_username: kv-aditya-srivatsa
facebook_username: kvaditya.srivatsa
#xing_username: jekyll
#pinterest_username: jekyll
#youtube_username: jekyll
#googleplus_username: +jekyll
#orcid_username: 0000-0000-0000-0000

# Additional icon links
#additional_links:
#- title: Link name
#  icon: Font Awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#  url: Link url (eg. https://google.com)
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  I am a 3rd year undergrad student at the [International Institute of Information Technology-Hyderabad](https://www.iiit.ac.in/)(IIIT-H), 
  currently pursuing a Dual Degree towards a Bachelors in Computer Science and Masters by Research in Computational Linguistics. I have a keen interest in Natural Language Processing & 
  Machine Learning, and have worked on several research projects involving the same.
  
  As a part of my masters, I am presently pursuing my research at the [MT-NLP Lab](https://ltrc.iiit.ac.in/nlpmt/) 
  at the [Language Technology Research Centre](https://ltrc.iiit.ac.in/) (LTRC) at IIIT-H, with 
  [Dr. Manish Shrivastava](https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=&cad=rja&uact=8&ved=2ahUKEwju5c2Ug_TuAhWFgdgFHcxoAFcQFjAAegQIARAD&url=http%3A%2F%2Fscholar.google.co.in%2Fcitations%3Fuser%3DsIvMnGQAAAAJ%26hl%3Den&usg=AOvVaw2YHxW1do-XZ_ILcU1ZIXPe) as my research advisor.
  
  Apart from NLP, I have also come to develop an interest in Congnitive Sciences. Recently, more so in how Psycholinguistics can shed light upon how 
  our meta-cognitive beliefs may affect common behavioural decisions.

#You can even add paragraphs by using empty lines like this and add anything else [markdown](https://www.markdownguide.org/getting-started#what-is-markdown) supports such as
#  - Lists
#  - Tables
#  - <a href="google.com">Links</a>
#  - Images ![alt text](/images/landscape-trees.jpg "Trees")

content:

  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
    
      #- layout: left
      #  title: Project name
      #  link: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
      #  link_text: Link Text
      #  additional_links:
      #    - title:  Github page for project (eg. sproogen/modern-resume-theme)
      #      icon: fab fa-github
      #      url: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
      #    - title:  Github page for project (eg. sproogen/modern-resume-theme)
      #      icon: fab fa-github
      #      url: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
      #  quote: >
      #    Short overview of the project (optional)
      #  description: | # this will include new lines to allow paragraphs
      #    Description about the work on/with the project
      
      - layout: left
        title: Sep 2020 - Jan 2021 
        #quote: (Sep 2020 - Present)
        description: | # this will include new lines
          Mukund Choudhary, [KV Aditya Srivatsa](https://kvadityasrivatsa.github.io/), Ishan Sanjeev Upadhyay, Praneet Kumar, Priyanka Srivastava \
          **Is convenient secure ? Exploring the impact of metacognitive beliefs in password selection**\
          *7th Annual Conference of Congnitive Science (ACCS7).* 2021 <mark>Conference</mark>
          
      - layout: left
        title: Oct 2020 - Present 
        additional_links:
          - title:  kvadityasrivatsa/text_simplification
            icon: fab fa-github
            url: https://github.com/kvadityasrivatsa/text_simplification
        #quote: (Sep 2020 - Present)
        description: | # this will include new lines
          **Controllable Text Simplification**: Dealing with simplification as a monolingual translation task, while using control tokens to generate fine-tuned output.
          Exploring both Statistical Machine Translation and Transformer based methods.

      - layout: left
        title: Sep 2020 - Present 
        #quote: (Sep 2020 - Present)
        description: | # this will include new lines
          **Extracting Latent Lexical Hierarchy from Word Embeddings**: Using word embeddings such as Word2Vec, GloVe & FastText to predict pairwise word hierarchy, with an aim towards an automated graph-based lexical hierarchy database.

      - layout: left
        title: Mar 2020 - May 2020
        #quote: (Oct 2019 - Nov 2019)
        description: | # this will include new lines to allow paragraphs
          **Evaluating Word Embeddings for Hindi**: Comparing Word2Vec, GloVe & FastText upon their performances on various intrinsic and extrinsic tasks for Hindi.

      - layout: left
        title: Oct 2019 - Nov 2019
        #quote: (Oct 2019 - Nov 2019)
        description: | # this will include new lines to allow paragraphs
          **Extractive Summarization in Hindi**: Exploring and implementing statistical methods for extractive summarization for a Hindi news dataset.
   
      - layout: left
        title: Mar 2019 - Apr 2019
        #quote: (Oct 2019 - Nov 2019)
        description: | # this will include new lines to allow paragraphs
          **Detection of Intra-Word Code-Switching in English-Indian Language Pairs**: Evaluating the performance of Morfessor on detecting  intra-word code-switching in English-Indian language based Twitter data. 
   
   
  - title: Experience
  
    layout: list
    content:
    
    
      #- layout: right
      #  title: Company name
      #  sub_title: Job title
      #  caption: Date Range (eg. November 2016 - present)
      #  link: Link to company (optional)
      #  quote: >
      #    Short description of the company (optional)
      #  description: | # this will include new lines to allow paragraphs
      #    Description of role
         
         
      - layout: right
        title: Teaching Assistant 
        sub_title: (CL3.202) Computational Linguistics - II at IIIT-H
        caption: (Aug 2020 - Nov 2020)
        link: https://iiit.ac.in
        #quote: Short description of the company (optional)
        description: | # this will include new lines to allow paragrap  
            **Involved Topics and Resources (Keywords)**: Computational Semantics, Word Sense Disambiguation, WordNet, Indic-WordNet, VerbNet, FrameNet,
            Formal Notations, Lambda Calculus, Predicate Logic, Semantic Role Labelling, Computational Discourse Analysis, Coreference Chains, Anaphora Resolution, 
            Sentiment Analysis, Computational Pragmatics, Dialogue Systems.
          
          
  - title: Education
    layout: list
    content:
    
      #- layout: top-right
      #  title: Institution name
      #  sub_title: Qualifications (eg. BA Performing Arts)
      #  caption: Date Range (eg. 2016 - 2019)
      #  quote: >
      #    Short institution or course description (optional)
      #  description: | # this will include new lines to allow paragraphs
      #    Description of qualification
           
      
      - layout: top-left
        title: IIIT-Hyderabad 
        sub_title: B.Tech Computer Science | MS by Research in Computational Linguistics
        caption: (2018 - Present)
        #quote: 
        description: | # this will include new lines to allow paragraphs
          ![IIIT-H Logo](/images/iiith.png "International Institute of Information Technology")
          
      
      - layout: top-left
        title:  Sardar Patel Vidyalaya 
        sub_title: High School
        caption: (2003 - 2018)
        #quote: Short institution or course description (optional)
        description: | # this will include new lines to allow paragraphs
          ![SPV Logo](/images/spv.png "Sardar Patel Vidyalaya")
          
          
  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
    
      Outside of work, I love to spend time on DIY pet projects, playing the flute, Minecraft and Ultimate Frisbee. 
      
      I also take an immense interest in Astronomy, that led me to be a member of my institue's Astronomy Club as well as
      a part of events such as [**CanSat**](http://www.cansatcompetition.com/). 
 

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
